import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-blue-500 h-full'>
        <Link href='/login'>LOGIN</Link>
        {/* <h1 className="text-3xl font-bold underline">
          Hello world!
        </h1> */}
        <div className='m-0 space-y-2'>
          <img src='dots.svg' alt={'Dots'} className='md:w-[10vw] md:block hidden' ></img>
          <img src='dots.svg' alt={'Dots'} className='md:w-[10vw] md:block hidden ml-[10%]' ></img>
          <img src='dots.svg' alt={'Dots'} className='md:w-[10vw] md:block hidden' ></img>
        </div>
      </main>
    </>
  )
}
